controllers:
    resource:
        path: ../src/UberTop/RideBookingContext/Adapters/Primary/Symfony/Controllers/
        namespace: App\UberTop\RideBookingContext\Adapters\Primary\Symfony\Controllers
    type: attribute
